namespace CrossFire.Replay.Protocol.Game;

/// <summary>Client round-type enum. Stored in map info.</summary>
public enum RoundType : int
{
    None = 0x0,
    TeamMatch = 0x1,
    TeamDeathMatch = 0x2,
    Hidden = 0x3,
    DeathMatch = 0x4,
    Nano = 0x5,
    Special = 0x6,
    TeamMatchDeath = 0x7,
    CsMatch = 0x8,
    Escape = 0x9,
    Tutorial = 0xA,
    AiMod = 0xB,
    Nano3 = 0xC,
    TrainingWeapon = 0xD,
    Nano4 = 0xE,
    Wave = 0xF,
    Hidden2Elimination = 0x10,
    Hidden2Injection = 0x11,
    Nano5 = 0x12,
    Nano6 = 0x13,
    SuperSoldierTd = 0x14,
    LightTeamMatch = 0x15,
    Spy = 0x16,
    CaptainMatch = 0x17,
    AiMod2 = 0x18,
    SuperSoldierTm = 0x19,
    AiBotTeamDeathMatch = 0x1A,
    SheepMode = 0x1B,
    AiBotTeamDeathMatchMix = 0x1C,
    KingsDeathMatch = 0x1D,
    Tm2Mode = 0x1E,
    AiMod3 = 0x1F,
    AiBotTeamMatch = 0x20,
    CtcMode = 0x21,
    BigHead = 0x22,
    EscapeTeamMatch = 0x23,
    WeaponMasterDeathMatch = 0x24,
    BattleTeamDeathMatchMode = 0x25,
    BattleOccupationMode = 0x26,
    BossBattle = 0x27,
    WeaponMasterTeamDeathMatch = 0x28,
    GuessMeMode = 0x29,
    BattleRoyalDm = 0x2A,
    BattleRoyalTd = 0x2B,
    BattleRoyalDuo = 0x2C,
    AimMode = 0x2D,
    StealthBombing = 0x2E,
    GuessMe2Mode = 0x2F,
    KnockbackMode = 0x30,
    TigMode = 0x31,
    PveRankMatch = 0x32,
    GrandTeamDeathMatch = 0x33,
    AiExtraMode = 0x34,
    StrategicBombingTeamMatch = 0x35,
    MazeMode = 0x36,
    Max = 0x37,
}
